package com.git4u.tt_wallet_android.rx

object RxBusTag {

    //set result
    const val SET_RESULT_OK = "RESULT_OK"
    const val SCANNER_ADDRESS_TAG = "SCANNER_ADDRESS_TAG"
    const val SCANNER_AMOUNT_TAG = "SCANNER_AMOUNT_TAG"
    const val SET_AUTH_OK = "AUTH_OK"
    //tag
    const val SET_WALLET_ID_RESULT_OK = "SET_WALLET_ID_RESULT_OK"
    const val UPDATE_WALLET_NAME_OK = "UPDATE_WALLET_NAME_OK"
    const val SELECT_ADDRESS_OK = "SELECT_ADDRESS_OK"
    const val SELECT_WALLET_OK = "SELECT_WALLET_OK"
    const val SELECT_COIN_OK = "SELECT_COIN_OK"
    const val UPDATE_MINER_FEE_EDIT_BEAN_OK = "UPDATE_MINER_FEE_EDIT_BEAN_OK"
    const val UPDATE_RECEIPT_ADDRESS_OK = "UPDATE_RECEIPT_ADDRESS_OK"
    const val UPDATE_RECEIPT_ADDRESS_UI_IN_THUNDER = "UPDATE_RECEIPT_ADDRESS_UI_IN_THUNDER"
    const val BACK_UP_IDENTIFY_FLOW_OK = "BACK_UP_IDENTIFY_FLOW_OK"
    const val RECEIPT_ADDRESS_PRESS_TOOLBAR_BACK = "RECEIPT_ADDRESS_PRESS_TOOLBAR_BACK"

    const val SELECT_THUNDER_ADDRESS_OK = "SELECT_THUNDER_ADDRESS_OK"
    const val SELECT_THUNDER_WALLET_OK = "SELECT_THUNDER_WALLET_OK"

    const val TRANSFER_COIN_ACTION_OK = "TRANSFER_COIN_ACTION_OK"

    // activity finish
    const val ASSET_FRAGMENT_FINISH = "ASSET_FRAGMENT_FINISH"
    const val SEARCH_COIN_FRAGMENT_FINISH = "SEARCH_COIN_FRAGMENT_FINISH"
    const val COMMON_ADDRESS_FINISH = "COMMON_ADDRESS_FINISH"
    const val REVIEW_ADDRESS_FINISH = "REVIEW_ADDRESS_FINISH"

    // bottom sheet dialog fragment
    const val PAYMENT_DETAIL_DIALOG_ON_CLICK_RECEIPT_ADDRESS_ITEM =
        "PAYMENT_DETAIL_DIALOG_ON_CLICK_RECEIPT_ADDRESS_ITEM"
    const val PAYMENT_DETAIL_DIALOG_ON_CLICK_PAY_ADDRESS_ITEM =
        "PAYMENT_DETAIL_DIALOG_ON_CLICK_PAY_ADDRESS_ITEM"
    const val PAYMENT_DETAIL_DIALOG_ON_CLICK_MINER_FEE_ITEM =
        "PAYMENT_DETAIL_DIALOG_ON_CLICK_MINER_FEE_ITEM"
    const val PAYMENT_DETAIL_DIALOG_ON_CLICK_NEXT_STEP = "PAYMENT_DETAIL_DIALOG_ON_CLICK_NEXT_STEP"
    const val PAYMENT_DETAIL_DIALOG_DISMISS = "PAYMENT_DETAIL_DIALOG_DISMISS"

    const val PICK_WALLET_DIALOG_DISMISS = "PICK_WALLET_DIALOG_DISMISS"
    const val PICK_WALLET_DIALOG_DISMISS_RESHOW_PAYMENT_DETAIL_DIALOG =
        "PICK_WALLET_DIALOG_DISMISS_RESHOW_PAYMENT_DETAIL_DIALOG"
    const val MINER_FEE_EDITOR_DIALOG_DISMISS = "MINER_FEE_EDITOR_DIALOG_DISMISS"
    const val REGISTER_SEND_MINER_FEE_EDIT_BEAN = "REGISTER_SEND_MINER_FEE_EDIT_BEAN"
    const val SEND_MINER_FEE_EDIT_BEAN = "SEND_MINER_FEE_EDIT_BEAN"

    const val UPDATE_PAYMENT_DETAIL_DIALOG_ADDRESS_OK = "UPDATE_PAYMENT_DETAIL_DIALOG_ADDRESS_OK"
    const val UPDATE_PAYMENT_DETAIL_DIALOG_INPUT_COMMENT =
        "UPDATE_PAYMENT_DETAIL_DIALOG_INPUT_COMMENT"

    // update thunder record list
    const val UPDATE_THUNDER_RECORD_LIST = "UPDATE_THUNDER_RECORD_LIST"

    // chat
    const val UPDATE_CREATE_GROUP_MEMBER_LIST = "UPDATE_CREATE_GROUP_MEMBER_LIST"
    const val SECRET_CHAT_MODE_CHANGE = "SECRET_CHAT_MODE_CHANGE"
    const val UPDATE_USER_INFO = "UPDATE_USER_INFO"
    const val EXIT_CHAT_ROOM = "EXIT_CHAT_ROOM"
    const val UPDATE_CONTACT_LIST = "UPDATE_CONTACT_LIST"
    const val UPDATE_CHAT_ROOM_LIST = "UPDATE_CHAT_ROOM_LIST"
    const val SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
    const val SEND_COIN_REQUEST = "SEND_COIN_REQUEST"
    const val OPEN_CHAT_ROOM = "OPEN_CHAT_ROOM"

    // chat socket
    const val LOAD_CHAT_ROOM_HISTORY_WITH_SOCKET = "LOAD_CHAT_ROOM_HISTORY_WITH_SOCKET"
    const val NOTIFY_CHAT_ROOM_UPDATE_WITH_SOCKET = "NOTIFY_CHAT_ROOM_UPDATE_WITH_SOCKET"
    const val LOGIN_ROCKET_CHAT_WITH_SOCKET = "LOGIN_ROCKET_CHAT_WITH_SOCKET"
    const val SOCKET_FAILURE = "SOCKET_FAILURE"
    const val NOTIFY_CHAT_SECRET_MODE_UPDATE = "NOTIFY_CHAT_SECRET_MODE_UPDATE"

    // ct wallet list
    const val CT_WALLET_REFRESH = "CT_WALLET_REFRESH"
    const val CT_WALLET_QUERY_API = "CT_WALLET_QUERY_API"

    // red envelope
    const val RED_ENVELOPE_TRANSACTION_COMPLETE = "RED_ENVELOPE_TRANSACTION_COMPLETE"

    const val UPDATE_ME_INFO = "UPDATE_ME_INFO"

    const val AGREE_PRIVACY_POLICY = "AGREE_PRIVACY_POLICY"

    const val FINISH_SELECT_BACKUP_METHOD_ACTIVITY = "FINISH_SELECT_BACKUP_METHOD_ACTIVITY"

}
